// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // DDL (migrate) butuh session pooler port 5432; DIRECT_URL disediakan
    // bila runtime kelak pindah ke transaction pooler (6543).
    // Nama POSTGRES_* datang dari integrasi Supabase–Vercel; lihat src/lib/env.ts.
    url:
      process.env.DIRECT_URL ||
      process.env.POSTGRES_URL_NON_POOLING ||
      process.env.DATABASE_URL ||
      process.env.POSTGRES_PRISMA_URL ||
      "",
  },
});
